### ISSUE TITLE
ARISA_FIXED command logs errors for non-existent versions

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#429]
## The Bug
ARISA_FIXED command logs errors for non-existent versions, instead of commenting "command execution failed".

```
Caused by: net.rcarz.jiraclient.RestException: 400 : {"errorMessages":[],"errors":{"fixVersions":"Version name 'Future version 1.14+' is not valid"}}
        at net.rcarz.jiraclient.RestClient.request(RestClient.java:171)
        at net.rcarz.jiraclient.RestClient.request(RestClient.java:193)
        at net.rcarz.jiraclient.RestClient.request(RestClient.java:238)
        at net.rcarz.jiraclient.RestClient.post(RestClient.java:328)
        at net.rcarz.jiraclient.RestClient.post(RestClient.java:372)
        at net.rcarz.jiraclient.Issue$FluentTransition.realExecute(Issue.java:482)
        ... 26 common frames omitted
```

## Example Ticket

https://bugs.mojang.com/browse/MCTEST-103

## Expected behavior

Comment "command execution failed" under the ticket. Ideally the error message should also be included in that comment.

**Comment by SunCatMC** [comment]
My ticket is not a good example as I had a breakpoint stopping the execution and thus it couldn't get to adding the comment

**Comment by SunCatMC** [comment]
or do you mean the actual arisa failing, not my local version?

**Comment by Marcono1234** [comment]
Related to #413

**Comment by NeunEinser** [comment]
> 
> 
> or do you mean the actual arisa failing, not my local version?

Issues are always about master ;)

**Comment by urielsalis** [comment]
Might be hard to do as it caches the action for later
@SPGoding thoughts?

**Comment by SPGoding** [comment]
As we're now [already checking the version beforehand](https://github.com/mojira/arisa-kt/blob/e78b83b6f45d77b886556f3acf9a914040f3c7cf/src/main/kotlin/io/github/mojira/arisa/modules/commands/FixedCommand.kt#L10-L12), this error should not happen anymore. Or did you mean something else?
