### ISSUE TITLE
LanguageModule fails

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#660]
## The Bug
```
19:42:14.612 [main] ERROR Arisa - [RESPONSE] [MCPE-128317] [Language] Failed
java.io.IOException: 403 from language API: code=error.notAllowed, message=token param is missing
        at io.github.mojira.arisa.infrastructure.LanguageDetectionApiKt.getLanguage(LanguageDetectionApi.kt:81)
        at io.github.mojira.arisa.ModuleRegistry$3.invoke(ModuleRegistry.kt:223)
        at io.github.mojira.arisa.ModuleRegistry$3.invoke(ModuleRegistry.kt:52)
        at arrow.syntax.function.PartialsKt$partially1$2.invoke(partials.kt:773)
        at io.github.mojira.arisa.modules.LanguageModule.getDetectedLanguage(LanguageModule.kt:67)
        at io.github.mojira.arisa.modules.LanguageModule.access$getDetectedLanguage(LanguageModule.kt:14)
        at io.github.mojira.arisa.modules.LanguageModule$invoke$$inlined$with$lambda$1.invokeSuspend(LanguageModule.kt:29)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at arrow.typeclasses.MonadContinuation$bind$$inlined$suspendCoroutineUninterceptedOrReturn$lambda$1.invoke(MonadContinuations.kt:36)
        at arrow.typeclasses.MonadContinuation$bind$$inlined$suspendCoroutineUninterceptedOrReturn$lambda$1.invoke(MonadContinuations.kt:15)
        at arrow.core.extensions.EitherMonad$flatMap$1.invoke(either.kt:123)
        at arrow.core.extensions.EitherMonad$flatMap$1.invoke(either.kt:115)
        at arrow.core.EitherKt.flatMap(Either.kt:881)
        at arrow.core.extensions.EitherMonad$DefaultImpls.flatMap(either.kt:123)
        at arrow.core.extensions.either.monad.EitherMonadKt$monad_singleton$1.flatMap(EitherMonad.kt:21)
        at arrow.core.extensions.either.monad.EitherMonadKt$monad_singleton$1.flatMap(EitherMonad.kt:21)
        at arrow.typeclasses.MonadContinuation.flatMap(MonadContinuations.kt)
        at arrow.typeclasses.MonadContinuation.bind$suspendImpl(MonadContinuations.kt:34)
        at arrow.typeclasses.MonadContinuation.bind(MonadContinuations.kt)
        at io.github.mojira.arisa.modules.LanguageModule$invoke$$inlined$with$lambda$1.invokeSuspend(LanguageModule.kt:27)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at arrow.typeclasses.MonadContinuation$bind$$inlined$suspendCoroutineUninterceptedOrReturn$lambda$1.invoke(MonadContinuations.kt:36)
        at arrow.typeclasses.MonadContinuation$bind$$inlined$suspendCoroutineUninterceptedOrReturn$lambda$1.invoke(MonadContinuations.kt:15)
        at arrow.core.extensions.EitherMonad$flatMap$1.invoke(either.kt:123)
        at arrow.core.extensions.EitherMonad$flatMap$1.invoke(either.kt:115)
        at arrow.core.EitherKt.flatMap(Either.kt:881)
        at arrow.core.extensions.EitherMonad$DefaultImpls.flatMap(either.kt:123)
        at arrow.core.extensions.either.monad.EitherMonadKt$monad_singleton$1.flatMap(EitherMonad.kt:21)
        at arrow.core.extensions.either.monad.EitherMonadKt$monad_singleton$1.flatMap(EitherMonad.kt:21)
        at arrow.typeclasses.MonadContinuation.flatMap(MonadContinuations.kt)
        at arrow.typeclasses.MonadContinuation.bind$suspendImpl(MonadContinuations.kt:34)
        at arrow.typeclasses.MonadContinuation.bind(MonadContinuations.kt)
        at io.github.mojira.arisa.modules.LanguageModule$invoke$$inlined$with$lambda$1.invokeSuspend(LanguageModule.kt:24)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at arrow.typeclasses.MonadContinuation$bind$$inlined$suspendCoroutineUninterceptedOrReturn$lambda$1.invoke(MonadContinuations.kt:36)
        at arrow.typeclasses.MonadContinuation$bind$$inlined$suspendCoroutineUninterceptedOrReturn$lambda$1.invoke(MonadContinuations.kt:15)
        at arrow.core.extensions.EitherMonad$flatMap$1.invoke(either.kt:123)
        at arrow.core.extensions.EitherMonad$flatMap$1.invoke(either.kt:115)
        at arrow.core.EitherKt.flatMap(Either.kt:881)
        at arrow.core.extensions.EitherMonad$DefaultImpls.flatMap(either.kt:123)
        at arrow.core.extensions.either.monad.EitherMonadKt$monad_singleton$1.flatMap(EitherMonad.kt:21)
        at arrow.core.extensions.either.monad.EitherMonadKt$monad_singleton$1.flatMap(EitherMonad.kt:21)
        at arrow.typeclasses.MonadContinuation.flatMap(MonadContinuations.kt)
        at arrow.typeclasses.MonadContinuation.bind$suspendImpl(MonadContinuations.kt:34)
        at arrow.typeclasses.MonadContinuation.bind(MonadContinuations.kt)
        at io.github.mojira.arisa.modules.LanguageModule$invoke$$inlined$with$lambda$1.invokeSuspend(LanguageModule.kt:23)
        at io.github.mojira.arisa.modules.LanguageModule$invoke$$inlined$with$lambda$1.invoke(LanguageModule.kt)
        at arrow.typeclasses.MonadFx$monad$wrapReturn$1.invokeSuspend(Monad.kt:108)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:129)
        at arrow.typeclasses.MonadFx$DefaultImpls.monad(Monad.kt:109)
        at arrow.core.extensions.EitherMonadFx.monad(either.kt:136)
        at arrow.core.extensions.EitherMonadFx.monad(either.kt:133)
        at arrow.core.extensions.EitherKt.fx(either.kt:235)
        at io.github.mojira.arisa.modules.LanguageModule.invoke(LanguageModule.kt:22)
        at io.github.mojira.arisa.ModuleRegistry$getModuleResult$1$1.invoke(ModuleRegistry.kt:89)
        at io.github.mojira.arisa.ModuleRegistry$getModuleResult$1$1.invoke(ModuleRegistry.kt:52)
        at io.github.mojira.arisa.ModuleRegistry.tryExecuteModule(ModuleRegistry.kt:101)
        at io.github.mojira.arisa.ModuleRegistry.access$tryExecuteModule(ModuleRegistry.kt:52)
        at io.github.mojira.arisa.ModuleRegistry$getModuleResult$1.invoke(ModuleRegistry.kt:89)
        at io.github.mojira.arisa.ModuleRegistry$getModuleResult$1.invoke(ModuleRegistry.kt:52)
        at arrow.syntax.function.PartialsKt$partially2$1.invoke(partials.kt:775)
        at io.github.mojira.arisa.ModuleExecutor.executeModule(ModuleExecutor.kt:81)
        at io.github.mojira.arisa.ModuleExecutor.execute(ModuleExecutor.kt:43)
        at io.github.mojira.arisa.ArisaMainKt.main(ArisaMain.kt:75)
        at io.github.mojira.arisa.ArisaMainKt.main(ArisaMain.kt)
```

**Comment by Marcono1234** [comment]
Is this still the case? If I understand it correctly #659 has fixed this specific (HTTP 403) issue.
