### ISSUE TITLE
Arisa fails to transition WEB tickets

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#661]
## The Bug
Most likely because components have been added, `UPDATE` fails for WEB tickets now.

Example:
```
net.rcarz.jiraclient.JiraException: Failed to transition issue WEB-4459
    at net.rcarz.jiraclient.Issue$FluentTransition.realExecute(Issue.java:484)
    at net.rcarz.jiraclient.Issue$FluentTransition.execute(Issue.java:518)
    at io.github.mojira.arisa.infrastructure.jira.FunctionsKt$applyFluentTransition$1$1.invokeSuspend(Functions.kt:241)
    at io.github.mojira.arisa.infrastructure.jira.FunctionsKt$applyFluentTransition$1$1.invoke(Functions.kt)
    at arrow.core.Either$Companion.catch(Either.kt:862)
    at arrow.core.Either$Companion.catch(Either.kt:858)
    at io.github.mojira.arisa.infrastructure.jira.FunctionsKt$applyFluentTransition$1.invokeSuspend(Functions.kt:240)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
    at io.github.mojira.arisa.infrastructure.jira.FunctionsKt.applyFluentTransition(Functions.kt:239)
    at io.github.mojira.arisa.infrastructure.jira.FunctionsKt.access$applyFluentTransition(Functions.kt:1)
    at io.github.mojira.arisa.infrastructure.jira.FunctionsKt$applyIssueChanges$2.invoke(Functions.kt:210)
    at io.github.mojira.arisa.infrastructure.jira.FunctionsKt$applyIssueChanges$2.invoke(Functions.kt)
    at arrow.syntax.function.PartialsKt$partially1$2.invoke(partials.kt:773)
    at arrow.syntax.function.PartialsKt$partially1$1.invoke(partials.kt:771)
    at io.github.mojira.arisa.modules.HelpersKt.tryRunAll(Helpers.kt:84)
    at io.github.mojira.arisa.in
```

**Comment by violine1101** [comment]
Only appears to happen on old tickets that don't have Component set.
