### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#707]
## The Bug
```
16:44:16.484 [main] ERROR Arisa - [RESPONSE] [MCPE-122850] [UpdateLinked] Failed
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
        at java.base/java.util.ArrayList.grow(ArrayList.java:238)
        at java.base/java.util.ArrayList.grow(ArrayList.java:243)
        at java.base/java.util.ArrayList.add(ArrayList.java:486)
        at java.base/java.util.ArrayList.add(ArrayList.java:499)
        at org.apache.commons.collections.map.ListOrderedMap.put(ListOrderedMap.java:215)
        at net.sf.json.JSONObject._setInternal(JSONObject.java:2691)
        at net.sf.json.JSONObject.setInternal(JSONObject.java:2736)
        at net.sf.json.JSONObject._fromJSONObject(JSONObject.java:944)
        at net.sf.json.JSONObject.fromObject(JSONObject.java:155)
        at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:108)
        at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
        at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
        at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
        at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
        at net.sf.json.JSONArray._fromJSONArray(JSONArray.java:1096)
        at net.sf.json.JSONArray.fromObject(JSONArray.java:121)
        at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:105)
        at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
        at net.sf.json.JSONObject._processValue(JSONObject.java:2655)
        at net.sf.json.JSONObject.processValue(JSONObject.java:2721)
        at net.sf.json.JSONObject.element(JSONObject.java:1786)
        at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:1036)
        at net.sf.json.JSONObject.fromObject(JSONObject.java:159)
        at net.sf.json.util.JSONTokener.nextValue(JSONTokener.java:348)
        at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:1008)
        at net.sf.json.JSONObject.fromObject(JSONObject.java:159)
        at net.sf.json.util.JSONTokener.nextValue(JSONTokener.java:348)
        at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:1008)
        at net.sf.json.JSONObject.fromObject(JSONObject.java:159)
        at net.sf.json.util.JSONTokener.nextValue(JSONTokener.java:348)
        at net.sf.json.JSONArray._fromJSONTokener(JSONArray.java:1131)
```

**Comment by Marcono1234** [comment]
The REST JSON response for neither MCPE-122850 nor MCPE-123020 seems to be that large, so we probably have a memory leak?
Was someone with access to the server able to take a heap dump?

**Comment by SPGoding** [comment]
Sorry, I didn't take one before restarting it.

**Comment by Marcono1234** [comment]
No worries, but might be good to keep in mind in case an `OutOfMemoryError` occurs again.
